"""Browser-based API client — uses patchright to make requests from a real browser context.

stoken is generated by the browser's JS environment automatically, eliminating expiration issues.
Used for high-risk operations: search, recommend, greet, batch-greet.

Supports two modes:
  1. CDP mode (preferred): connects to user's existing Chrome via DevTools Protocol
  2. Patchright mode (fallback): launches a headless Chromium instance
"""
import sys
import time
from pathlib import Path
from types import TracebackType
from typing import Any, cast
from urllib.parse import urlencode

from patchright.sync_api import sync_playwright

from boss_agent_cli.api import endpoints
from boss_agent_cli.api.throttle import RequestThrottle
from boss_agent_cli.auth.browser import _DEFAULT_CDP_URL as CDP_DEFAULT_URL

HOME_URL = "https://www.zhipin.com/"
SEARCH_PAGE_URL = "https://www.zhipin.com/web/geek/jobs"


def _pick_existing_platform_page(context: Any) -> Any | None:
	"""优先复用已存在的 zhipin 页面，避免新建 CDP page 导航时销毁执行上下文。"""
	for page in context.pages:
		try:
			url = page.url or ""
		except Exception:
			continue
		if "zhipin.com" in url:
			return page
	return None


class RecruiterChatTabRequired(RuntimeError):
	"""招聘者操作（issue #217 修复路径）需要用户已打开 chat/index 页。

	不自动新开 tab：实测会触发 BOSS 反爬，把用户当前 tab 踢到首页。
	友好做法是返回明确指引，让用户自己打开。
	"""

	def __init__(self) -> None:
		super().__init__(
			"recruiter chat tab not found in CDP Chrome — "
			"please open https://www.zhipin.com/web/chat/index in your "
			"Chrome (CDP-attached) and retry."
		)

# 超时常量
_CDP_PROBE_TIMEOUT = 3           # CDP 探测 HTTP 超时（秒）
_CDP_CONNECT_TIMEOUT_MS = 5000   # CDP 建连超时（毫秒）
_NAV_TIMEOUT_MS = 15000          # 页面导航超时（毫秒）
_HEADLESS_NETWORKIDLE_GRACE_MS = 3000  # headless 预热的额外宽限，避免卡满 30s
_SEARCH_RESPONSE_TIMEOUT_MS = 8000      # 搜索页真实 joblist 响应等待超时（毫秒）

# macOS / Linux / Windows Chrome user data 默认路径
_CHROME_USER_DATA_CANDIDATES = [
	Path.home() / "Library/Application Support/Google/Chrome",              # macOS
	Path.home() / ".config/google-chrome",                                  # Linux
	Path.home() / "AppData/Local/Google/Chrome/User Data",                  # Windows
]


class BrowserSession:
	"""Persistent browser session that makes API calls via page.evaluate(fetch).

	Tries CDP connection to user's Chrome first; falls back to headless patchright.
	"""

	def __init__(self, cookies: dict[str, Any], user_agent: str, *, delay: tuple[float, float] = (1.5, 3.0), cdp_url: str | None = None, logger: Any = None) -> None:
		self._throttle = RequestThrottle(delay)
		# patchright / BridgeClient 运行时创建；注解为 Any 让 mypy 对外部依赖放行
		self._pw: Any = None
		self._browser: Any = None
		self._context: Any = None
		self._page: Any = None
		self._cookies = cookies
		self._user_agent = user_agent
		self._started = False
		self._cdp_url = cdp_url
		self._is_cdp = False
		self._own_context = False  # 是否由我们创建的 context（需要在 close 时清理）
		self._logger = logger
		self._bridge_client: Any = None
		self._is_bridge = False

	def _log(self, message: str) -> None:
		"""通过注入的 logger 输出，受 --log-level 控制。"""
		if self._logger:
			self._logger.info(message)
		else:
			print(message, file=sys.stderr)

	def _ensure_started(self) -> None:
		if self._started:
			return

		# 优先尝试 Bridge 模式（Chrome 扩展 + daemon，零配置）
		if self._try_bridge():
			return

		self._pw = sync_playwright().start()

		# 第二优先：CDP 连接用户 Chrome（真实指纹 + 天然登录态）
		if self._try_cdp():
			return

		# 兜底：启动 headless patchright
		self._start_headless()

	def _try_bridge(self) -> bool:
		"""尝试通过 Browser Bridge（Chrome 扩展 + daemon）连接。"""
		try:
			from boss_agent_cli.bridge.client import BridgeClient
			client = BridgeClient()
			if not client.is_running():
				return False
			if not client.is_extension_connected():
				self._log("[boss] Bridge daemon 运行中但扩展未连接")
				return False
			self._bridge_client = client
			self._started = True
			self._is_cdp = False
			self._is_bridge = True
			self._log("[boss] Bridge 模式连接成功（Chrome 扩展 + daemon）")
			return True
		except Exception:
			return False

	def _try_cdp(self) -> bool:
		"""Try connecting to user's Chrome via CDP.

		Attempts in order:
		  1. Explicit cdp_url if provided
		  2. Default http://localhost:9222 (+ auto WS fallback)
		  3. WebSocket URL from Chrome's DevToolsActivePort file
		"""
		urls_to_try: list[str] = []
		seen: set[str] = set()

		def add_url(candidate: str | None) -> None:
			if candidate and candidate not in seen:
				urls_to_try.append(candidate)
				seen.add(candidate)

		# 先尝试 WebSocket 端点，避免 connect_over_cdp(http://...) 在部分环境长时间卡住。
		if self._cdp_url and self._cdp_url.startswith("ws"):
			add_url(self._cdp_url)
		elif self._cdp_url:
			add_url(self._fetch_ws_url(self._cdp_url))
			add_url(self._cdp_url)

		add_url(self._fetch_ws_url(CDP_DEFAULT_URL))
		add_url(CDP_DEFAULT_URL)

		# 从 DevToolsActivePort 文件读取 WebSocket URL
		add_url(self._read_devtools_active_port())

		for url in urls_to_try:
			if self._try_connect(url):
				return True
		return False

	def _try_connect(self, url: str) -> bool:
		"""Attempt a single CDP connection, reusing user's existing context.

		Reuses the first existing browser context (preserves login state and
		avoids Chrome's automation detection on new contexts). Only creates
		a new context when none exists.
		"""
		try:
			self._browser = self._pw.chromium.connect_over_cdp(url, timeout=_CDP_CONNECT_TIMEOUT_MS)
			contexts = self._browser.contexts

			if contexts:
				# 复用用户现有 context（保留登录态 + 规避 automation 检测）
				self._context = contexts[0]
				self._own_context = False  # 非我们创建，close 时不关闭
			else:
				# 没有已存在 context，创建新的并注入 cookies
				self._context = self._browser.new_context()
				if self._cookies:
					self._context.add_cookies([
						{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
						for name, value in self._cookies.items()
					])
				self._own_context = True

			reused_page = _pick_existing_platform_page(self._context)
			if reused_page is not None:
				self._page = reused_page
			else:
				self._page = self._context.new_page()
				# CDP 模式下用较长超时 + commit 级等待（避免 networkidle 卡住）
				try:
					self._page.goto(HOME_URL, wait_until="commit", timeout=_NAV_TIMEOUT_MS)
				except Exception:
					pass  # 即使导航超时，页面 JS 环境已可用
			self._started = True
			self._is_cdp = True
			reuse_label = "复用用户 context + 现有页面" if reused_page is not None else ("复用用户 context" if not self._own_context else "新建 context")
			self._log(f"[boss] CDP 连接成功 ({url})，{reuse_label}")
			return True
		except Exception:
			if self._browser:
				try:
					self._browser.close()
				except Exception:
					pass
				self._browser = None
			return False

	@staticmethod
	def _fetch_ws_url(http_url: str) -> str | None:
		"""Fetch WebSocket debugger URL from Chrome's /json/version endpoint."""
		import httpx
		try:
			resp = httpx.get(f"{http_url}/json/version", timeout=_CDP_PROBE_TIMEOUT, trust_env=False)
			payload = resp.json()
			if not isinstance(payload, dict):
				return None
			return cast("str | None", payload.get("webSocketDebuggerUrl"))
		except (httpx.HTTPError, ValueError, KeyError):
			return None

	@staticmethod
	def _read_devtools_active_port() -> str | None:
		"""Read Chrome's DevToolsActivePort file to get WS endpoint."""
		for user_data_dir in _CHROME_USER_DATA_CANDIDATES:
			port_file = user_data_dir / "DevToolsActivePort"
			if port_file.exists():
				try:
					lines = port_file.read_text().strip().splitlines()
					if len(lines) >= 2:
						port = lines[0].strip()
						ws_path = lines[1].strip()
						return f"ws://127.0.0.1:{port}{ws_path}"
				except Exception:
					continue
		return None

	def _start_headless(self) -> None:
		"""Fallback: launch headless patchright Chromium."""
		self._browser = self._pw.chromium.launch(headless=True)
		self._context = self._browser.new_context(
			user_agent=self._user_agent,
			viewport={"width": 1280, "height": 800},
			locale="zh-CN",
			timezone_id="Asia/Shanghai",
		)
		self._own_context = True
		self._context.add_cookies([
			{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
			for name, value in self._cookies.items()
		])
		self._page = self._context.new_page()
		self._page.goto(HOME_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		try:
			self._page.wait_for_load_state("networkidle", timeout=_HEADLESS_NETWORKIDLE_GRACE_MS)
		except Exception as e:
			# zhipin 首页常驻请求较多，headless 模式下不一定能进入 networkidle；
			# 页面 JS 环境已可用时，继续直接发起 fetch 请求更稳。
			self._log(f"[boss] headless 首页未进入 networkidle（{e}），继续直接发起请求")
		self._started = True
		self._is_cdp = False
		self._log("[boss] CDP 不可用（提示：需以 --remote-debugging-port=9222 启动 Chrome），降级到 headless patchright")

	def _navigate_for_search(self, data: dict[str, Any]) -> None:
		"""先导航到真实搜索页，建立和前端一致的运行时上下文。"""
		params: dict[str, Any] = {}
		if query := data.get("query"):
			params["query"] = str(query)
		if city := data.get("city"):
			params["city"] = str(city)
		target = SEARCH_PAGE_URL
		if params:
			target = f"{target}?{urlencode(params)}"
		try:
			self._page.goto(target, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		except Exception as e:
			self._log(f"[boss] 搜索页导航未完全完成（{e}），继续尝试页内搜索请求")

	def _fetch_json_in_page(
		self,
		method: str,
		url: str,
		*,
		params: dict[str, Any] | None = None,
		data: dict[str, Any] | None = None,
		referer: str,
	) -> dict[str, Any]:
		"""在当前页面上下文里直接发 fetch 请求并返回 JSON。"""
		result = self._page.evaluate("""
			async ({method, url, params, data, referer}) => {
				try {
					let fetchUrl = url;
					if (params && Object.keys(params).length > 0) {
						const sp = new URLSearchParams();
						for (const [k, v] of Object.entries(params)) {
							if (v !== null && v !== undefined) sp.append(k, String(v));
						}
						fetchUrl = url + '?' + sp.toString();
					}

					const options = {
						method: method,
						credentials: 'include',
						headers: {
							'Accept': 'application/json, text/plain, */*',
							'Referer': referer,
							'X-Requested-With': 'XMLHttpRequest',
						},
					};

					if (method === 'POST' && data) {
						options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
						const formData = new URLSearchParams();
						for (const [k, v] of Object.entries(data)) {
							formData.append(k, String(v));
						}
						options.body = formData.toString();
					}

					const resp = await fetch(fetchUrl, options);
					return await resp.json();
				} catch (e) {
					return {code: -1, message: e.message, zpData: {}};
				}
			}
		""", {"method": method, "url": url, "params": params or {}, "data": data, "referer": referer})
		return cast("dict[str, Any]", result)

	def _cdp_http_url(self) -> str:
		"""Resolve the CDP HTTP endpoint used by raw websocket helpers."""
		if self._cdp_url and self._cdp_url.startswith("http"):
			return self._cdp_url.rstrip("/")
		return CDP_DEFAULT_URL

	def _search_request_via_raw_cdp(self, url: str, data: dict[str, Any], referer: str) -> dict[str, Any] | None:
		"""Use a raw CDP temp page for search to avoid patchright CDP attach instability."""
		cdp_http_url = self._cdp_http_url()
		if not self._fetch_ws_url(cdp_http_url):
			return None
		params: dict[str, str] = {}
		if query := data.get("query"):
			params["query"] = str(query)
		if city := data.get("city"):
			params["city"] = str(city)
		search_page_url = SEARCH_PAGE_URL
		if params:
			search_page_url = f"{search_page_url}?{urlencode(params)}"
		return _cdp_fetch_in_temp_page(cdp_http_url, search_page_url, "POST", url, params=None, data=data, referer=referer)

	def _detail_request_via_raw_cdp(self, url: str, params: dict[str, Any], referer: str) -> dict[str, Any] | None:
		"""Use a raw CDP temp page for detail when httpx stoken refresh fails."""
		cdp_http_url = self._cdp_http_url()
		if not self._fetch_ws_url(cdp_http_url):
			return None
		job_id = str(params.get("encryptJobId", ""))
		page_params = {"jid": job_id} if job_id else {}
		page_url = endpoints.WEB_GEEK_JOB_URL
		if page_params:
			page_url = f"{page_url}?{urlencode(page_params)}"
		return _cdp_fetch_in_temp_page(cdp_http_url, page_url, "GET", url, params=params, data=None, referer=referer)

	def _consume_search_page_response(self, url: str, data: dict[str, Any]) -> dict[str, Any]:
		"""等待真实搜索页自己发出的 joblist 响应。"""
		with self._page.expect_response(
			lambda resp: (
				resp.request.method == "POST"
				and url in resp.url
			),
			timeout=_SEARCH_RESPONSE_TIMEOUT_MS,
		) as response_info:
			self._navigate_for_search(data)

		resp = response_info.value
		return cast("dict[str, Any]", resp.json())

	def _search_request(self, url: str, data: dict[str, Any], referer: str) -> dict[str, Any]:
		"""搜索专用请求：优先消费真实页面响应，超时后降级为页内 fetch。"""
		last_error: Exception | None = None
		for attempt in range(2):
			try:
				result = self._consume_search_page_response(url, data)
			except Exception as e:
				last_error = e
				self._log(f"[boss] 未等到真实搜索页响应（{e}），降级为页内 fetch")
				try:
					self._navigate_for_search(data)
					result = self._fetch_json_in_page("POST", url, data=data, referer=referer)
				except Exception as fetch_error:
					last_error = fetch_error
					if attempt == 0:
						self._log(f"[boss] 搜索页内 fetch 失败（{fetch_error}），重试一次")
						continue
					raise
			if attempt == 0 and isinstance(result, dict) and result.get("code") == endpoints.CODE_STOKEN_EXPIRED:
				self._log("[boss] 搜索返回 code 37，重建搜索页上下文后重试一次")
				continue
			return cast("dict[str, Any]", result)
		if last_error is not None:
			raise last_error
		return {"code": -1, "message": "search request failed", "zpData": {}}

	# ── Core request via browser fetch() ─────────────────────────────

	def request(self, method: str, url: str, *, params: dict[str, Any] | None = None, data: dict[str, Any] | None = None) -> dict[str, Any]:
		self._throttle.wait()

		referer = endpoints.REFERER_MAP.get(url, f"{endpoints.BASE_URL}/")

		if method == "POST" and url == endpoints.SEARCH_URL and data:
			try:
				raw_cdp_result = self._search_request_via_raw_cdp(url, data, referer)
			except Exception as e:
				self._log(f"[boss] 原生 CDP 搜索失败（{e}），回退到浏览器附着链路")
			else:
				if raw_cdp_result is not None:
					self._throttle.mark()
					return cast("dict[str, Any]", raw_cdp_result)

		if method == "GET" and url == endpoints.DETAIL_URL and params:
			try:
				raw_cdp_result = self._detail_request_via_raw_cdp(url, params, referer)
			except Exception as e:
				self._log(f"[boss] 原生 CDP 详情失败（{e}），回退到浏览器附着链路")
			else:
				if raw_cdp_result is not None:
					self._throttle.mark()
					return cast("dict[str, Any]", raw_cdp_result)

		self._ensure_started()


		# Bridge 模式：通过扩展 fetch
		if self._is_bridge and self._bridge_client:
			import urllib.parse
			full_url = url
			if params:
				full_url = f"{url}?{urllib.parse.urlencode(params)}"
			result = self._bridge_client.fetch_json(
				full_url,
				method=method,
				data=data,
				referer=referer,
			)
			self._throttle.mark()
			return cast("dict[str, Any]", result)

		# 搜索接口对页面上下文更敏感：先进入真实搜索页，再发页内请求更稳定。
		if method == "POST" and url == endpoints.SEARCH_URL and data:
			result = self._search_request(url, data, referer)
			self._throttle.mark()
			return cast("dict[str, Any]", result)

		# Playwright 模式（CDP 或 headless）
		result = self._fetch_json_in_page(method, url, params=params, data=data, referer=referer)
		self._throttle.mark()
		return cast("dict[str, Any]", result)

	# ── Arbitrary JS evaluation (CDP-only, raw websocket) ────────────

	def evaluate_js(self, script: str, arg: Any = None) -> Any:
		"""Run JS in the user's recruiter chat tab via raw CDP websocket.

		Required for recruiter send_message (issue #217): we reach into the
		招聘者 chat page's Vue 2 instance to call geek-list.geekClick() +
		editor.sendText(). The normal BrowserSession.request fetch path can't
		do that — it runs JS in a blank tab BrowserSession owns, not in the
		user's recruiter tab.

		Why raw CDP instead of patchright: attaching patchright to another
		tab we didn't create via new_page() triggers 'Frame was detached'
		errors when that page navigates or re-renders (Vue SFC rebuilds
		frame tree). Raw CDP is a stateless RPC — we just send
		Runtime.evaluate and read the result, no session book-keeping.

		Intentionally does NOT call _ensure_started(): patchright's
		connect_over_cdp enumerates every tab's frame tree on attach, which
		can race with Vue re-renders on the recruiter page and crash the
		Node driver before we even get to our evaluate call. evaluate_js
		only needs the CDP HTTP endpoint reachable — not patchright.

		Only works in CDP mode (user has chrome://<devtools port>/json
		reachable and the recruiter chat tab open). Bridge/headless modes
		have no access to the user's Vue runtime.
		"""
		if self._is_bridge:
			raise RuntimeError("evaluate_js requires CDP mode (bridge mode has no access to user Chrome)")
		cdp_url = self._cdp_url or CDP_DEFAULT_URL
		return _cdp_evaluate_in_chat_tab(cdp_url, script, arg)

	def evaluate_js_with_chat_events(self, script: str, arg: Any = None, *, listen_ms: int = 3000) -> dict[str, Any]:
		"""Run JS in the recruiter chat tab and collect short-lived chat WS events.

		Used by recruiter send_message verification to distinguish a real chat send
		from UI-only draft mutation or suggestion traffic.
		"""
		if self._is_bridge:
			raise RuntimeError("evaluate_js_with_chat_events requires CDP mode (bridge mode has no access to user Chrome)")
		cdp_url = self._cdp_url or CDP_DEFAULT_URL
		return _cdp_evaluate_with_chat_events_in_chat_tab(cdp_url, script, arg, listen_ms=listen_ms)

	# ── Lifecycle ────────────────────────────────────────────────────

	@property
	def is_cdp(self) -> bool:
		"""Whether this session is using CDP connection to user's Chrome."""
		return self._is_cdp

	def close(self) -> None:
		if self._is_bridge and self._bridge_client:
			try:
				self._bridge_client.close_window()
			except Exception:
				pass
			self._bridge_client = None
			self._started = False
			return

		if self._is_cdp:
			# CDP 模式：关闭我们创建的 page 和 context，不关闭用户浏览器
			if self._page and self._own_context:
				try:
					self._page.close()
				except Exception:
					pass
			elif self._page and self._context and self._page not in getattr(self._context, "pages", []):
				try:
					self._page.close()
				except Exception:
					pass
			if self._own_context and self._context:
				try:
					self._context.close()
				except Exception:
					pass
		else:
			# Headless 模式：关闭整个浏览器实例
			if self._browser:
				try:
					self._browser.close()
				except Exception:
					pass
		if self._pw:
			try:
				self._pw.stop()
			except Exception:
				pass
		self._started = False

	def __enter__(self) -> "BrowserSession":
		return self

	def __exit__(
		self,
		exc_type: type[BaseException] | None,
		exc_val: BaseException | None,
		exc_tb: TracebackType | None,
	) -> None:
		self.close()


# ─── Raw CDP helper for evaluate_js ──────────────────────────────────────

def _pick_chat_target_ws(cdp_http_url: str) -> str:
	import json as _json
	import urllib.request

	list_url = cdp_http_url.rstrip("/") + "/json"
	try:
		with urllib.request.urlopen(list_url, timeout=3) as resp:
			tabs = _json.load(resp)
	except Exception as exc:
		raise RuntimeError(f"cannot reach CDP at {list_url}: {exc}") from exc

	for t in tabs:
		if t.get("type") == "page" and "/web/chat/index" in t.get("url", ""):
			target_ws = t.get("webSocketDebuggerUrl")
			if target_ws:
				return cast("str", target_ws)
	raise RecruiterChatTabRequired()


def _build_eval_expression(script: str, arg: Any) -> str:
	import json as _json

	if arg is not None:
		return f"({script})({_json.dumps(arg, ensure_ascii=False)})"
	return script


def _carve_utf8_bits(bs: bytes) -> list[str]:
	out: list[str] = []
	i = 0
	while i < len(bs):
		for length in range(min(len(bs) - i, 240), 4, -1):
			try:
				text = bs[i : i + length].decode("utf-8")
			except UnicodeDecodeError:
				continue
			if len(text) >= 5 and all(ch.isprintable() or ch in "\n\r\t" for ch in text):
				out.append(text)
				i += length
				break
		else:
			i += 1
	return out

def _cdp_evaluate_in_chat_tab(cdp_http_url: str, script: str, arg: Any) -> Any:
	"""Send Runtime.evaluate to the BOSS recruiter chat tab via raw CDP.

	Bypasses patchright entirely — avoids 'Frame was detached' errors when
	the Vue page re-renders during our call. Wraps the caller's script as
	`(fnSrc)(arg)` when arg is provided, so the script can be a JS expression
	that evaluates to a function of one argument (mirrors patchright's
	`page.evaluate(script, arg)` contract used by the PoC).
	"""
	import json as _json

	import websockets.sync.client as _ws_client

	target_ws = _pick_chat_target_ws(cdp_http_url)
	expression = _build_eval_expression(script, arg)

	with _ws_client.connect(target_ws, max_size=8 * 1024 * 1024) as ws:
		ws.send(_json.dumps({
			"id": 1,
			"method": "Runtime.evaluate",
			"params": {
				"expression": expression,
				"returnByValue": True,
				"awaitPromise": True,
			},
		}))
		deadline = time.time() + 30.0
		while time.time() < deadline:
			raw = ws.recv(timeout=max(0.1, deadline - time.time()))
			msg = _json.loads(raw)
			if msg.get("id") != 1:
				continue
			err = msg.get("error")
			if err:
				raise RuntimeError(f"CDP Runtime.evaluate error: {err}")
			result = msg.get("result", {}).get("result", {})
			if "value" in result:
				return result["value"]
			# Exception in JS side
			exc_details = msg.get("result", {}).get("exceptionDetails")
			if exc_details:
				raise RuntimeError(f"JS exception: {exc_details.get('text')} — {exc_details.get('exception', {}).get('description', '')[:300]}")
			return result
		raise RuntimeError("CDP Runtime.evaluate timed out after 30s")


def _cdp_evaluate_with_chat_events_in_chat_tab(
	cdp_http_url: str, script: str, arg: Any, *, listen_ms: int
) -> dict[str, Any]:
	import base64 as _base64
	import json as _json

	import websockets.sync.client as _ws_client

	target_ws = _pick_chat_target_ws(cdp_http_url)
	expression = _build_eval_expression(script, arg)

	with _ws_client.connect(target_ws, max_size=8 * 1024 * 1024) as ws:
		ws.send(_json.dumps({"id": 1, "method": "Network.enable"}))
		ws.send(_json.dumps({
			"id": 2,
			"method": "Runtime.evaluate",
			"params": {
				"expression": expression,
				"returnByValue": True,
				"awaitPromise": True,
			},
		}))

		events: list[dict[str, Any]] = []
		eval_value: Any = None
		eval_done = False
		deadline = time.time() + 30.0
		listen_deadline: float | None = None

		while True:
			now = time.time()
			if eval_done and listen_deadline is not None and now >= listen_deadline:
				return {"value": eval_value, "events": events}
			if now >= deadline:
				raise RuntimeError("CDP Runtime.evaluate timed out after 30s")

			timeout = 0.1 if eval_done and listen_deadline is not None else max(0.1, deadline - now)
			try:
				raw = ws.recv(timeout=timeout)
			except TimeoutError:
				continue

			msg = _json.loads(raw)
			msg_id = msg.get("id")
			if msg_id == 2:
				err = msg.get("error")
				if err:
					raise RuntimeError(f"CDP Runtime.evaluate error: {err}")
				result = msg.get("result", {}).get("result", {})
				exc_details = msg.get("result", {}).get("exceptionDetails")
				if exc_details:
					raise RuntimeError(
						f"JS exception: {exc_details.get('text')} — "
						f"{exc_details.get('exception', {}).get('description', '')[:300]}"
					)
				eval_value = result.get("value", result)
				eval_done = True
				listen_deadline = time.time() + (listen_ms / 1000.0)
				continue

			method = msg.get("method")
			if method not in ("Network.webSocketFrameSent", "Network.webSocketFrameReceived"):
				continue
			frame = msg.get("params", {}).get("response", {})
			if frame.get("opcode") not in (1, 2):
				continue

			payload_data = frame.get("payloadData", "")
			try:
				bs = _base64.b64decode(payload_data, validate=False)
			except Exception:
				bs = payload_data.encode("utf-8", errors="ignore")
			if len(bs) < 30:
				continue

			events.append({
				"ts": time.time(),
				"kind": "ws_send" if method.endswith("Sent") else "ws_recv",
				"bytes": len(bs),
				"utf8_bits": _carve_utf8_bits(bs)[:10],
			})


def _cdp_fetch_in_temp_page(
	cdp_http_url: str,
	page_url: str,
	method: str,
	api_url: str,
	*,
	params: dict[str, Any] | None,
	data: dict[str, Any] | None,
	referer: str,
) -> dict[str, Any]:
	"""Open a temporary CDP page, navigate to a same-origin page, then run fetch there."""
	import json as _json
	import urllib.request

	import websockets.sync.client as _ws_client

	create_url = cdp_http_url.rstrip("/") + "/json/new?" + page_url
	close_url_template = cdp_http_url.rstrip("/") + "/json/close/{target_id}"
	target_id = ""
	target_ws = ""

	try:
		req = urllib.request.Request(create_url, method="PUT")
		with urllib.request.urlopen(req, timeout=5) as resp:
			payload = _json.load(resp)
			target_id = cast("str", payload["id"])
			target_ws = cast("str", payload["webSocketDebuggerUrl"])
	except Exception as exc:
		raise RuntimeError(f"cannot create CDP search page: {exc}") from exc

	script = """
		async ({method, apiUrl, params, data, referer}) => {
			let fetchUrl = apiUrl;
			if (params && Object.keys(params).length > 0) {
				const sp = new URLSearchParams();
				for (const [k, v] of Object.entries(params)) {
					if (v !== null && v !== undefined) sp.append(k, String(v));
				}
				fetchUrl = apiUrl + '?' + sp.toString();
			}
			const options = {
				method,
				credentials: 'include',
				headers: {
					'Accept': 'application/json, text/plain, */*',
					'Referer': referer,
					'X-Requested-With': 'XMLHttpRequest',
				},
			};
			if (method === 'POST' && data) {
				options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
				const formData = new URLSearchParams();
				for (const [k, v] of Object.entries(data)) {
					if (v !== null && v !== undefined) formData.append(k, String(v));
				}
				options.body = formData.toString();
			}
			const resp = await fetch(fetchUrl, options);
			return await resp.json();
		}
	"""

	try:
		with _ws_client.connect(target_ws, max_size=8 * 1024 * 1024) as ws:
			ws.send(_json.dumps({
				"id": 1,
				"method": "Page.enable",
			}))
			ws.send(_json.dumps({
				"id": 2,
				"method": "Runtime.enable",
			}))
			ws.send(_json.dumps({
				"id": 3,
				"method": "Page.navigate",
				"params": {"url": page_url},
			}))

			deadline = time.time() + 15.0
			load_fired = False
			while time.time() < deadline:
				raw = ws.recv(timeout=max(0.1, deadline - time.time()))
				msg = _json.loads(raw)
				if msg.get("method") == "Page.loadEventFired":
					load_fired = True
					break
			if not load_fired:
				raise RuntimeError("CDP Page.navigate timed out after 15s")

			expression = _build_eval_expression(script, {
				"method": method,
				"apiUrl": api_url,
				"params": params or {},
				"data": data,
				"referer": referer,
			})
			ws.send(_json.dumps({
				"id": 4,
				"method": "Runtime.evaluate",
				"params": {
					"expression": expression,
					"returnByValue": True,
					"awaitPromise": True,
				},
			}))

			eval_deadline = time.time() + 30.0
			while time.time() < eval_deadline:
				raw = ws.recv(timeout=max(0.1, eval_deadline - time.time()))
				msg = _json.loads(raw)
				if msg.get("id") != 4:
					continue
				err = msg.get("error")
				if err:
					raise RuntimeError(f"CDP Runtime.evaluate error: {err}")
				result = msg.get("result", {}).get("result", {})
				if "value" in result:
					value = result["value"]
					return cast("dict[str, Any]", value)
				exc_details = msg.get("result", {}).get("exceptionDetails")
				if exc_details:
					raise RuntimeError(
						f"JS exception: {exc_details.get('text')} — "
						f"{exc_details.get('exception', {}).get('description', '')[:300]}"
					)
			raise RuntimeError("CDP search evaluate timed out after 30s")
	finally:
		if target_id:
			try:
				req = urllib.request.Request(close_url_template.format(target_id=target_id), method="GET")
				with urllib.request.urlopen(req, timeout=5):
					pass
			except Exception:
				pass
